/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.List;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(),
         "app should have a greeting");
    }

    
// 1. Given that I a new --shopper--, when I begin 
// shopping, then I expect my --cart-- to be empty.
    @Test
    void testEmptyCart(){
        
        //Setup
        Cart cut = new Cart(); 

        //Execute
        List<Item> itemsList = cut.getItems();

        //Assert
        assertEquals(0, itemsList.size());

    }

// 2. Given I have an empty --cart--,
//    when I add an ---Item---, 
//    then I expect to the price reflect the sum of all the Items
//    in my cart.
    @Test
    Void totalPriceWhenItemAdded(){

        //Setup
        // Cart cut = new Cart(); 

        //Execute


        //Assert



    }



}



/***
 
Class

1. Shopper
2. cart
3. item
4. 

 */