/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        List<String> ls = new ArrayList<String>();
        ls.add("Null");
        ls.add("String");
        ls.add("Pass");

        // System.out.println(new App().getGreeting());
        for (String s : ls) {
            System.out.println(s);
        }
    }
}
